import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const Akkurat = localFont({
  src: "./fonts/Akkurat.ttf",
  variable: "--font-akkurat",
  weight: "400",
});
const AkkuratBold = localFont({
  src: "./fonts/Akkurat-Bold.ttf",
  variable: "--font-akkurat-bold",
  weight: "400",
});
const ChronicleDisplay = localFont({
  src: "./fonts/Chronicle-Display.otf",
  variable: "--font-chronicle-display",
  weight: "375",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${Akkurat.variable} ${AkkuratBold.variable} ${ChronicleDisplay.variable} antialiased`}
      >
        {/* <Navbar /> */}
        {children}
        <Footer/>
      </body>
    </html>
  );
}
